### ISSUE TITLE
Can't auto skip a whole song

### ISSUE THREAD

**Issue by 7peanuts** [neRok00/mb_SkipOverSong#4]
When the tag value is set to `true` or `yes`, MusicBee will not automatically skip and play the next song, but will stop playing.

![20230924171421](https://github.com/neRok00/mb_SkipOverSong/assets/82173614/e1486cab-a5e3-4531-a197-0482d2bf189d)

Skipping with timestamp is work well.

**Comment by neRok00** [comment]
I don't know if I will investigate the problem, because I don't actually use the plugin any more!

I discovered if you right click on a song and Edit, then go to Settings tab, there are options there to do exactly what this plugin does (you can "Exclude from playback">"Only when shuffling", and set start and end times). I wonder if these settings were always there?

Also I discovered how good Auto-Playlist's are. Instead of using this plugin to not play songs during shuffle, I just build playlists that filter out songs with certain tags, like if they have skip_over_song tag. I now tag and filter for so many things.

**Comment by 7peanuts** [comment]
> I discovered if you right click on a song and Edit, then go to Settings tab, there are options there to do exactly what this plugin does (you can "Exclude from playback">"Only when shuffling", and set start and end times).
> 
> Also I discovered how good Auto-Playlist's are.
I just build playlists that filter out songs with certain tags, like if they have skip_over_song tag.

Yes, I've seen it. This skip function is already available in the default settings.

But thank you all the same. 🥳
